name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Test
        run: ./gradlew test

      - name: Setup jfrog cli
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.ARTIFACTORY_ENV }}

      - name: Upload artifacts
        run: |
            # Configure gradle
            # jf gradlec --repo-deploy github-ci-jfrog --use-wrapper
            # Upload artifacts to artifactory
            jf gradle clean artifactoryPublish --build-name github-ci-build --build-number ${build_number}
            # Upload build-info to artifactory
            jf rt bp github-ci-build ${build_number}
        env:
          artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          build_number: ${{ github.run_id }}


#  build-release:
#    needs:
#      - build-snapshot
#    environment: release
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v3
#
#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'corretto'
#          java-version: '11'
#
#      - name: Build
#        run: ./gradlew build
#
#      - name: Publish to artifactory
#        run: ./gradlew artifactoryPublish -DisRelease=true
#        env:
#          artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
#          artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
#          build_number: ${{ github.run_id }}